version: "2"

linters:
  default: standard
  enable:
    - staticcheck
    - govet
    - errcheck
    - ineffassign
    - unused
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell
    - bodyclose
    - contextcheck

formatters:
  enable:
    - gofmt
    - goimports
    - golines

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
